# Generated by Django 3.0.5 on 2020-04-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wid', models.IntegerField(unique=True)),
                ('wfirstname', models.CharField(max_length=50)),
                ('wlastname', models.CharField(max_length=50)),
                ('wsalary', models.FloatField()),
                ('waddress', models.CharField(max_length=50)),
            ],
        ),
    ]
